### ISSUE TITLE
Avoid static inner classes!

### ISSUE THREAD

**Issue by carloslozano** [AdaptiveMe/adaptive-arp-android#19]
For example: 
* ```<repo>```/adaptive-arp-rt/mobile/src/main/java/me/adaptive/arp/impl/NetworkStatusDelegate.java
* This class defined ```NetworkStatusReceiver``` that is then referenced by AndroidManifest.xml:
```xml
<receiver android:name=".impl.NetworkStatusDelegate$NetworkStatusReceiver" android:enabled="true">
  <intent-filter>
    <action android:name="android.net.conn.CONNECTIVITY_CHANGE" />
  </intent-filter>
</receiver>
```
* This forces ```private static List<INetworkStatusListener> listeners;``` to be static.

Create a separate class for the ```NetworkStatusReceiver``` (not inner class):
* Make listeners non-static.
* Give ```NetworkStatusDelegate``` a protected getter method for the listeners.
* Use ```IAppRegistry``` to get ```NetworkStaticBridge``` and cast to ```(NetworkStatusDelegate)``` to access your protected getter method.

**Comment by fnva** [comment]
Solved by @kechis
